In [36]:
from sklearn.svm import SVC
import pandas as pd
from sklearn import datasets
from sklearn.model_selection import train_test_split

In [35]:
df = datasets.load_iris(as_frame=True).frame

In [3]:
df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0

In [5]:
df.isnull().sum()

sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
target               0
dtype: int64

In [7]:
df.shape

(150, 5)

In [8]:
# split data

X= df.drop("target", axis = 1)
y = df["target"]

In [9]:
X.head()

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [12]:
y.head()

0    0
1    0
2    0
3    0
4    0
Name: target, dtype: int64

In [13]:
# it is very important to scale the data
# in case of SVC we only scale input data not output
# in case of svr we do cale both i/p and o/p

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42, stratify=y
)

In [15]:
X_train.head()

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
98                 5.1               2.5                3.0               1.1
68                 6.2               2.2                4.5               1.5
19                 5.1               3.8                1.5               0.3
143                6.8               3.2                5.9               2.3
99                 5.7               2.8                4.1               1.3

In [19]:
# scaling
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [20]:
model = SVC()
model.fit(X_train_scaled, y_train)

SVC()

In [21]:
y_pred = model.predict(X_test_scaled)

In [26]:
from sklearn.metrics import accuracy_score, classification_report
print(f"Accuracy {accuracy_score(y_test, y_pred)}")
print(f"classification_report {classification_report(y_test, y_pred)}")

Accuracy 0.9333333333333333
classification_report               precision    recall  f1-score   support

           0       1.00      1.00      1.00        15
           1       0.88      0.93      0.90        15
           2       0.93      0.87      0.90        15

    accuracy                           0.93        45
   macro avg       0.93      0.93      0.93        45
weighted avg       0.93      0.93      0.93        45

In [28]:
# lets try with other kernal
model = SVC(kernel="linear") # by default RBF
model.fit(X_train_scaled, y_train)

y_pred = model.predict(X_test_scaled)

print(f"Accuracy {accuracy_score(y_test, y_pred)}")

Accuracy 0.9111111111111111

In [29]:
# lets try with other kernal
model = SVC(kernel="poly") # by default RBF
model.fit(X_train_scaled, y_train)

y_pred = model.predict(X_test_scaled)

print(f"Accuracy {accuracy_score(y_test, y_pred)}")

Accuracy 0.8666666666666667

In [30]:
# lets try with other kernal
model = SVC(kernel="sigmoid") # by default RBF
model.fit(X_train_scaled, y_train)

y_pred = model.predict(X_test_scaled)

print(f"Accuracy {accuracy_score(y_test, y_pred)}")

Accuracy 0.9111111111111111

In [33]:
# lets try with other kernal
c = [0.2, 0.4, 0.7, 1, 2, 3, 4, 6, 7, 8, 9]
for c_val in c:
    model = SVC(C = c_val,kernel="rbf") # by default RBF and c = 1
    model.fit(X_train_scaled, y_train)
    
    y_pred = model.predict(X_test_scaled)
    
    print(f"C = {c_val}, Accuracy {accuracy_score(y_test, y_pred)}")

C = 0.2, Accuracy 0.9111111111111111
C = 0.4, Accuracy 0.9111111111111111
C = 0.7, Accuracy 0.9333333333333333
C = 1, Accuracy 0.9333333333333333
C = 2, Accuracy 0.9111111111111111
C = 3, Accuracy 0.9111111111111111
C = 4, Accuracy 0.9333333333333333
C = 6, Accuracy 0.9333333333333333
C = 7, Accuracy 0.9333333333333333
C = 8, Accuracy 0.9333333333333333
C = 9, Accuracy 0.9333333333333333